### ISSUE TITLE
How to build/use the example

### ISSUE THREAD

**Issue by bilboed** [standard-ai/tracing-gstreamer#23]
Hi,

There are no docs on how to build/try `examples/videoenc.rs` in order to try what this looks like with tracy. Could someone provide this information ? Thanks

**Comment by SteveMcFarlin** [comment]
@bilboed It took me some time to get Tracy working with this crate. You might look at tracing-tracy for more examples. I have no idea if this code still works or not. I have not used Tracy other than to experiment with profiling our production pipelines, and that was nearly a year ago.

```
// This enables tracing for gstreamer. Additionally it will pipe the tracing out
// through the TracyLayer which sends the events to Tracy https://github.com/wolfpld/tracy
// This option should never be enabled in production. It is intended for debugging
// performance issues only.
let sub = tracing_subscriber::registry().with(tracing_tracy::TracyLayer::new());
tracing::subscriber::set_global_default(sub).expect("setting default subscriber failed");
gstreamer::debug_remove_default_log_function();
tracing_gstreamer::integrate_events();

gstreamer::debug_set_default_threshold(gstreamer::DebugLevel::Memdump);
gstreamer::init().expect("gst init");
tracing_gstreamer::integrate_spans();
 ```
```
tracing = "0.1.37"
tracing-futures = "0.2"
tracing-gstreamer = "0.5.0"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter"] }
tracing-tracy = "0.10.2"
```

**Comment by nagisa** [comment]
The example by default only uses the tracing-fmt subscriber in order to make the example self-contained. Since it is, `cargo run --example videoenc` should be sufficient to run it and see the results in your standard output. If you want to test this with tracy, you will have to check out the repository locally and modify the example code to add the tracy subscriber, similar to what @SteveMcFarlin shown.

Definitely refer to `tracing-tracy` documentation for integration guidance there. The two crates are otherwise entirely independent.
